KERNEL_DIR?=/lib/modules/$(shell uname -r)/build
PWD:=$(shell pwd)

obj-m+=demo.o
demo-objs+=driver3.o

Default:
	$(MAKE) -C $(KERNEL_DIR) M=$(PWD) modules

clear:
	rm -rf $(demo-objs) demo* [Mm]odule* 
